### PR TITLE
#56: Migrate Travis CI to GitHub Actions

### PR DESCRIPTION
**Pull request by Tiliavir**
This PR will use GitHub Actions instead of Travis.

- [x]  Fix release build - there is a permission issue : https://github.com/baloise/digital-signature/runs/1723155686?check_suite_focus=true

### CODE REVIEW

**Comment by arburk** [comment]
I guess the .travis.yml can be removed as well as the travis profile in pom.xml as soon as github actions are working properly

**Review by arburk — APPROVED** [review]
LGTM

**Comment by Tiliavir** [comment]
Hi @culmat: Seems to work 🥳

**Review by culmat — APPROVED** [review]
Cool 👍

**Pull request merged**
