### PR TITLE
Added Signature Class to XStream Allowlist

### PR DESCRIPTION
**Pull request by stefan-ernst**
This is necessary for Confluence 7.18+

https://confluence.atlassian.com/doc/preparing-for-confluence-7-18-1124175263.html#PreparingforConfluence7.18-XStreamupgrade

### CODE REVIEW

**Comment by realignedtechnologies** [comment]
Hi Olaf,

the plugin needs to be recompiled with the modified atlassian-plugin.xml and then installed over the previous version

Cheers

Stefan

**Comment by keyless-tracer** [comment]
Hello Stefan,

first of all thank you for your quick answers.
Is there an existing workflow for this, or is it the workflow awaiting approval?

Thanks
Olaf

**Review by culmat — COMMENTED** [review]
Thank you @stefan-ernst!

**Comment by culmat** [comment]
I now get the following error

`class com.baloise.confluence.digitalsignature.Signature cannot be cast to class com.baloise.confluence.digitalsignature.Signature (com.baloise.confluence.digitalsignature.Signature is in unnamed module of loader org.apache.felix.framework.BundleWiringImpl$BundleClassLoader @299b9277; com.baloise.confluence.digitalsignature.Signature is in unnamed module of loader org.apache.felix.framework.BundleWiringImpl$BundleClassLoader @297c4640)`

**Pull request merged**
